# def sql(update, context):
#     update.message.reply_text('<b><a href = "https://www.bitdegree.org/learn/sql-commands-list#andor">AND|OR</a></b>\n'
#                               '<b><a href = "https://www.bitdegree.org/learn/sql-commands-list#alter-table">ALTER TABLE</a></b>\n',
#                               parse_mode=telegram.ParseMode.HTML)
#     # "\n*[ALTER TABLE](https://www.bitdegree.org/learn/sql-commands-list#alter-table)*"
#     # "\n*[AS (alias)](https://www.bitdegree.org/learn/sql-commands-list#as-alias)*"
#     # "\n*[BETWEEN](https://www.bitdegree.org/learn/sql-commands-list#between)*"
#     # "\n*[CREATE DATABASE](https://www.bitdegree.org/learn/sql-commands-list#create-database)*"
#     # "\n*[CREATE TABLE](https://www.bitdegree.org/learn/sql-commands-list#create-table)*"
#     # "\n*[CREATE INDEX](https://www.bitdegree.org/learn/sql-commands-list#create-index)*"
#     # "\n*[CREATE VIEW](https://www.bitdegree.org/learn/sql-commands-list#create-view)*"
#     # "\n*[DELETE](https://www.bitdegree.org/learn/sql-commands-list#delete)*"
#     # "\n*[GRANT](https://www.bitdegree.org/learn/sql-commands-list#grant)*"
#     # "\n*[REVOKE](https://www.bitdegree.org/learn/sql-commands-list#revoke)*"
#     # "\n*[COMMIT](https://www.bitdegree.org/learn/sql-commands-list#commit)*"
#     # "\n*[ROLLBACK](https://www.bitdegree.org/learn/sql-commands-list#rollback)*"
#     # "\n*[SAVEPOINT](https://www.bitdegree.org/learn/sql-commands-list#savepoint)*"
#     # "\n*[DROP DATABASE](https://www.bitdegree.org/learn/sql-commands-list#drop-database)*"
#     # "\n*[DROP INDEX](https://www.bitdegree.org/learn/sql-commands-list#drop-index)*"
#     # "\n*[DROP TABLE](https://www.bitdegree.org/learn/sql-commands-list#drop-table)*"
#     # "\n*[EXISTS](https://www.bitdegree.org/learn/sql-commands-list#exists)*"
#     # "\n*[GROUP BY](https://www.bitdegree.org/learn/sql-commands-list#group-by)*"
#     # "\n*[HAVING](https://www.bitdegree.org/learn/sql-commands-list#having)*"
#     # "\n*[IN](https://www.bitdegree.org/learn/sql-commands-list#in)*"
#     # "\n*[INSERT INTO](https://www.bitdegree.org/learn/sql-commands-list#insert-into)*"
#     # "\n*[INNER JOIN](https://www.bitdegree.org/learn/sql-commands-list#inner-join)*"
#     # "\n*[LEFT JOIN](https://www.bitdegree.org/learn/sql-commands-list#left-join)*"
#     # "\n*[RIGHT JOIN](https://www.bitdegree.org/learn/sql-commands-list#right-join)*"
#     # "\n*[FULL JOIN](https://www.bitdegree.org/learn/sql-commands-list#full-join)*"
#     # "\n*[LIKE](https://www.bitdegree.org/learn/sql-commands-list#like)*"
#     # "\n*[ORDER BY](https://www.bitdegree.org/learn/sql-commands-list#order-by)*"
#     # "\n*[SELECT](https://www.bitdegree.org/learn/sql-commands-list#select)*"
#     # "\n*[SELECT DISTINCT](https://www.bitdegree.org/learn/sql-commands-list#select-distinct)*"
#     # "\n*[SELECT INTO](https://www.bitdegree.org/learn/sql-commands-list#select-into)*"
#     # "\n*[SELECT TOP](https://www.bitdegree.org/learn/sql-commands-list#select-top)*"
#     # "\n*[TRUNCATE TABLE](https://www.bitdegree.org/learn/sql-commands-list#truncate-table)*"
#     # "\n*[UNION](https://www.bitdegree.org/learn/sql-commands-list#union)*"
#     # "\n*[UNION ALL](https://www.bitdegree.org/learn/sql-commands-list#union-all)*"
#     # "\n*[UPDATE](https://www.bitdegree.org/learn/sql-commands-list#update)*"
#     # "\n*[WHERE](https://www.bitdegree.org/learn/sql-commands-list#where)*"